# -*- coding: utf-8 -*-
"""
Macedonian municipalities per the reorganization from 2004.
"""
from django.utils.translation import ugettext_lazy as _

MK_MUNICIPALITIES = (
    ('MK.AD', _(u'Aerodrom')),
    ('MK.AR', _(u'Aračinovo')),
    ('MK.BR', _(u'Berovo')),
    ('MK.TL', _(u'Bitola')),
    ('MK.BG', _(u'Bogdanci')),
    ('MK.VJ', _(u'Bogovinje')),
    ('MK.BS', _(u'Bosilovo')),
    ('MK.BN', _(u'Brvenica')),
    ('MK.BU', _(u'Butel')),
    ('MK.VA', _(u'Valandovo')),
    ('MK.VL', _(u'Vasilevo')),
    ('MK.VV', _(u'Vevčani')),
    ('MK.VE', _(u'Veles')),
    ('MK.NI', _(u'Vinica')),
    ('MK.VC', _(u'Vraneštica')),
    ('MK.VH', _(u'Vrapčište')),
    ('MK.GB', _(u'Gazi Baba')),
    ('MK.GV', _(u'Gevgelija')),
    ('MK.GT', _(u'Gostivar')),
    ('MK.GR', _(u'Gradsko')),
    ('MK.DB', _(u'Debar')),
    ('MK.DA', _(u'Debarca')),
    ('MK.DL', _(u'Delčevo')),
    ('MK.DK', _(u'Demir Kapija')),
    ('MK.DM', _(u'Demir Hisar')),
    ('MK.DE', _(u'Dolneni')),
    ('MK.DR', _(u'Drugovo')),
    ('MK.GP', _(u'Gjorče Petrov')),
    ('MK.ZE', _(u'Želino')),
    ('MK.ZA', _(u'Zajas')),
    ('MK.ZK', _(u'Zelenikovo')),
    ('MK.ZR', _(u'Zrnovci')),
    ('MK.IL', _(u'Ilinden')),
    ('MK.JG', _(u'Jegunovce')),
    ('MK.AV', _(u'Kavadarci')),
    ('MK.KB', _(u'Karbinci')),
    ('MK.KX', _(u'Karpoš')),
    ('MK.VD', _(u'Kisela Voda')),
    ('MK.KH', _(u'Kičevo')),
    ('MK.KN', _(u'Konče')),
    ('MK.OC', _(u'Koćani')),
    ('MK.KY', _(u'Kratovo')),
    ('MK.KZ', _(u'Kriva Palanka')),
    ('MK.KG', _(u'Krivogaštani')),
    ('MK.KS', _(u'Kruševo')),
    ('MK.UM', _(u'Kumanovo')),
    ('MK.LI', _(u'Lipkovo')),
    ('MK.LO', _(u'Lozovo')),
    ('MK.MR', _(u'Mavrovo i Rostuša')),
    ('MK.MK', _(u'Makedonska Kamenica')),
    ('MK.MD', _(u'Makedonski Brod')),
    ('MK.MG', _(u'Mogila')),
    ('MK.NG', _(u'Negotino')),
    ('MK.NV', _(u'Novaci')),
    ('MK.NS', _(u'Novo Selo')),
    ('MK.OS', _(u'Oslomej')),
    ('MK.OD', _(u'Ohrid')),
    ('MK.PE', _(u'Petrovec')),
    ('MK.PH', _(u'Pehčevo')),
    ('MK.PN', _(u'Plasnica')),
    ('MK.PP', _(u'Prilep')),
    ('MK.PT', _(u'Probištip')),
    ('MK.RV', _(u'Radoviš')),
    ('MK.RN', _(u'Rankovce')),
    ('MK.RE', _(u'Resen')),
    ('MK.RO', _(u'Rosoman')),
    ('MK.AJ', _(u'Saraj')),
    ('MK.SL', _(u'Sveti Nikole')),
    ('MK.SS', _(u'Sopište')),
    ('MK.SD', _(u'Star Dojran')),
    ('MK.NA', _(u'Staro Nagoričane')),
    ('MK.UG', _(u'Struga')),
    ('MK.RU', _(u'Strumica')),
    ('MK.SU', _(u'Studeničani')),
    ('MK.TR', _(u'Tearce')),
    ('MK.ET', _(u'Tetovo')),
    ('MK.CE', _(u'Centar')),
    ('MK.CZ', _(u'Centar-Župa')),
    ('MK.CI', _(u'Čair')),
    ('MK.CA', _(u'Čaška')),
    ('MK.CH', _(u'Češinovo-Obleševo')),
    ('MK.CS', _(u'Čučer-Sandevo')),
    ('MK.ST', _(u'Štip')),
    ('MK.SO', _(u'Šuto Orizari')),
)

